SELECT NAME, USERID, PWD, EMAIL, PHONE, ADMIN, JOINDATE
  FROM MEMBER;

INSERT INTO MEMBER(NAME, USERID, PWD, EMAIL, PHONE, ADMIN) 
VALUES ('박규영', 'parkgy', '1234', 'pgy@gmail.com', '010-1111-2222', 0);

SELECT NAME, USERID, PWD, EMAIL, PHONE, ADMIN, JOINDATE
  FROM MEMBER
 WHERE USERID = 'parkgy';

UPDATE MEMBER
   SET NAME='문채원', PWD='5678', EMAIL='mcw@gmail.com', 
       PHONE='010-3333-5555', ADMIN=1, JOINDATE='2020-08-20'
 WHERE USERID = 'parkgy';

DELETE FROM MEMBER WHERE USERID = 'test';

-- usercheck
SELECT PWD FROM MEMBER WHERE USERID = 'somi';





----------------------------------
SELECT USER FROM DUAL;

SELECT *
	FROM USER_TABLES ;
	
SELECT MAX(TITLE_NO)+1 FROM TITLE;

SELECT  * FROM title;

SELECT DEPT_NO, DEPT_NAME, FLOOR FROM DEPARTMENT ;





SELECT EMP_NO, EMP_NAME, TNO, MANAGER, SALARY, DNO, REGDATE, 
       EMAIL, TEL, PIC_URL, TITLE_NAME, DEPT_NAME, MANAGER_NAME 
  FROM VW_EMPLOYEE_JOIN;

INSERT INTO EMPLOYEE(EMP_NO, EMP_NAME, TNO, MANAGER, SALARY, DNO, EMAIL, PASSWD) VALUES(?, ?, ?, ?, ?, ?, ?, ?);

SELECT EMP_NO, EMP_NAME, TNO, MANAGER, SALARY, DNO, REGDATE, 
       EMAIL, TEL, PIC_URL, TITLE_NAME, DEPT_NAME, MANAGER_NAME 
  FROM VW_EMPLOYEE_JOIN
 	WHERE EMP_NO = 4380;

UPDATE EMPLOYEE 
	SET EMP_NAME ='아이유',
		TNO = '1',
		MANAGER ='1003',
		SALARY = '3000000',
		DNO = '10',
		REGDATE = SYSDATE ,
		EMAIL = 'nana@naver.com',
		TEL = '010-0000-0000',
		PIC_URL = 'adf'
	WHERE EMP_NO = ?;

DELETE FROM EMPLOYEE WHERE EMP_NO = ?;

----------------------------------------------------
--trigger--------------------------------------
CREATE TABLE TRI_TEST(
	NO NUMBER PRIMARY KEY,
	TXT VARCHAR2(20)
);

CREATE SEQUENCE TRI_TEST_SEQ
	START WITH 1
	INCREMENT BY 1;

--트리커를 이용하여 번호가 입력되도록
CREATE OR REPLACE TRIGGER TRI_TRI_TEXT_AUTOSEQ
BEFORE INSERT ON TRI_TEST
FOR EACH ROW
BEGIN
   IF Inserting AND :NEW.NO IS NULL THEN
      SELECT TRI_TEST_SEQ.NEXTVAL INTO :NEW.NO FROM DUAL;
   END IF;
END;

DROP TRIGGER TRI_TRI_TEST_AUTOSEQ;

INSERT INTO TRI_TEST VALUES (NULL,'TEST');

SELECT * FROM TRI_TEST;


-----------------------------------------------
SELECT CODE,NAME,PRICE,PICTUREURL,DESCRIPTION FROM product;

UPDATE PRODUCT 
	SET NAME = 'test2',
		PRICE = '30000',
		PICTUREURL = 'test.jpg',
		DESCRIPTION = 'tset이다'
	WHERE CODE = 2;

DELETE product WHERE code =2;

SELECT CODE,NAME,PRICE,PICTUREURL,DESCRIPTION FROM PRODUCT;



























